/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// This is a template file. Copy this to aws-exports.js and fill in your actual AWS configuration.

const awsmobile = {
    "aws_project_region": "YOUR_AWS_REGION",
    "aws_cognito_region": "YOUR_AWS_REGION",
    "aws_user_pools_id": "YOUR_USER_POOL_ID",
    "aws_user_pools_web_client_id": "YOUR_CLIENT_ID",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "YOUR_S3_BUCKET_NAME",
    "aws_user_files_s3_bucket_region": "YOUR_AWS_REGION",
    "aws_cognito_identity_pool_id": "YOUR_IDENTITY_POOL_ID"
};

export default awsmobile;
